### PR TITLE
Update crewStatsScene.cpp

### PR DESCRIPTION
**Pull request by Doronimmo**
Sprite-0001

### CODE REVIEW

**Comment by evanbowman** [comment]
It's an interesting suggestion, but I find this test harder to read, personally

**Comment by evanbowman** [comment]
What about using darker text? I would be ok with a change like this:
389223805-5ee27d14-411e-4226-9f91-39e9a1c59d41
If you remove bold_colors and don't pass it to Text::print in this file, you would get the default text palette for this tileset, which looks decent. But the white text against the tan background is too low contrast for the gba screen

**Comment by Doronimmo** [comment]
> What about using darker text? I would be ok with a change like this: 389223805-5ee27d14-411e-4226-9f91-39e9a1c59d41 If you remove bold_colors and don't pass it to Text::print in this file, you would get the default text palette for this tileset, which looks decent. But the white text against the tan background is too low contrast for the gba screen

this is actually the way it looks in the commit, I forgot to change the text color in the mockup 🤦‍♂️

**Comment by evanbowman** [comment]
Ah! Yeah it's a good suggestion. The palette that you're using is actually the default palette for this tile layer, so we don't even need the "bold_colors" variable. We can just delete it and any references to it in print functions.

**Comment by evanbowman** [comment]
Oh wait! Actually bold colors is used for crew icon selection hints, we don't want to delete it there I think.

**Comment by Doronimmo** [comment]
> Oh wait! Actually bold_colors is used for crew icon selection hints, we don't want to delete it there I think.

oh right

**Comment by Doronimmo** [comment]
Skyland-1

Skyland-2

**Comment by evanbowman** [comment]
I think it looks pretty good! The icon change is interesting too, I'm undecided about it, it think that part needs further discussion, but I'm ready to approve the text changes, they look good!

**Comment by Doronimmo** [comment]
> I think it looks pretty good! The icon change is interesting too, I'm undecided about it, it think that part needs further discussion, but I'm ready to approve the text changes, they look good!

Oh! Changed the icon as a test for compiling and kept it for version control (make sure I am not erasing my changes every time I update the version)

**Review by evanbowman — APPROVED** [review]
Looks good!

**Comment by evanbowman** [comment]
I wonder... I think the stats screen would look cleaner if there was a one-pixel line on top, so that the text isn't right up against the edge of the passport. I can take care of this after you merge.

**Pull request merged**
