### PR TITLE
Fade replace

### PR DESCRIPTION
**Pull request by Doronimmo**
replaced the old function with the new one

### CODE REVIEW

**Comment by Doronimmo** [comment]
reverted the intro, since it caused some weird visual glitch

**Comment by evanbowman** [comment]
Thanks! Eventually this needs to be done.
I'll explain the issue a bit more.

Originally, I had a fade function that ignored screen sync, forcing the fade to happen immediately. As the game grew in complexity, this started to cause tearing as CPU usage increased.

I created a second fade function to help resolve the issue. schedule_fade causes a screen fade to occur, but not until the next screen refresh.

schedule_fade is not quite a drop-in replacement for fade, in some cases. In certain cases, removing the fade() function will cause visual flicker, because the screen fade will not occur until screen redisplay, whereas the fade function causes the fade to happen instantaneously. The fade function is not good, and I'm slowly trying to replace it, but these changes need to be carefully tested.

**Comment by evanbowman** [comment]
Further explanation:
```
----------------------
|                    |
|    GBA Screen      |
|                    |
----------------------
|    Vertical Blank  |
----------------------
```
At the bottom of the gba screen, there's a region of offscreen scanlines called the vertical blank window. When the GBA hardware does a vertical sync, the game sleeps until an interrupt wakes it up at the beginning of the vertical blank window. Vertical blank is a safe time to update any screen effects, because the display controller is not processing any onscreen pixels, only the offscreen vertical blank region. The initial jam version of the game had simple logic, and both the display logic and the game update logic fit mostly in the vblank window, so it was pretty much safe to force an instantaneous fade without any synchronization. As the game update logic took more time, often the game update logic would occur while the display controller was redrawing the screen, and it was no longer safe to force a screen fade at random points in the codebase.

**Comment by evanbowman** [comment]
Continued:
But, at certain times, it just happens to be safe to cause a fade to happen immediately, because the update logic is fast enough to not run into the screen redraw period. In some cases, though, there is still tearing when calling `fade` and the `fade` function should be replaced with `schedule_fade`.

**Pull request closed without merging**
