### PR TITLE
Transitioned to an .sh script for repacking

### PR DESCRIPTION
**Pull request by Doronimmo**
Updated the readme with an sh script instead of the build.py

### CODE REVIEW

**Comment by Doronimmo** [comment]
Deleted the build.py since it was unnecessary and somewhat confusing

**Comment by evanbowman** [comment]
I'd be fine with changing from to a .sh script, can you help me find the repack.sh script? I don't see it yet in the list of file changes included in this PR

**Comment by Doronimmo** [comment]
> I'd be fine with changing from to a .py to a .sh script, can you help me find the repack.sh script? I don't see it yet in the list of file changes included in this PR

It was actually in the previous PR

**Comment by Doronimmo** [comment]
It is currently in the repository root dir

**Comment by Doronimmo** [comment]
[Here](https://github.com/evanbowman/skyland-beta/blob/master/repack.sh)

**Comment by evanbowman** [comment]
Oh! I understand now

I added a commit to master to include repack.sh in the files processed by encode_files.py. Most files are packaged automatically, but not files in the top level directory https://github.com/evanbowman/skyland-beta/commit/8abfce0833a50dc82faa8418814002abe3a3cca6#diff-c0f85957ae9ada8f50ac5f7b09a8ae16112fa35a00c6e22c3ca7f12ea85bc57cR214

**Review by evanbowman — APPROVED** [review]

**Pull request merged**
