### PR TITLE
choose ladder placement in surrender

### PR DESCRIPTION
**Pull request by Doronimmo**
draft, currently the ladder is placed but goblin is not and dialog is kinda messed up.

### CODE REVIEW

**Comment by evanbowman** [comment]
I added a utility script that might be helpful. There's a script called find-crew-slot that creates a block if it doesn't exist and gives you coordinates where the crew can be placed via a callback function:
https://github.com/evanbowman/skyland-beta/blob/74916548561a1a8ccbf777c3e111b909e0a859fa/scripts/event/quest/8.lisp#L43

**Comment by Doronimmo** [comment]
> I added a utility script that might be helpful. There's a script called find-crew-slot that creates a block if it doesn't exist and gives you coordinates where the crew can be placed via a callback function:
> 
> https://github.com/evanbowman/skyland-beta/blob/74916548561a1a8ccbf777c3e111b909e0a859fa/scripts/event/quest/8.lisp#L43

Actually tried with the utility script yesterday but didn't quite managed to understand how to implement it with the ss variable

**Comment by evanbowman** [comment]
> Actually tried with the utility script yesterday but didn't quite managed to understand how to implement it with the ss variable

The ss variable would no longer be needed. Sorry for the short variable names! An earlier version of the interpreter was unable to support variables longer than 4 letters, and there are still some old variable names that aren't very descriptive.

The ss variable holds slots that a character can be placed into.

The find-crew-slot script handles finding a slot or creating it if it doesn't exist, so there's no need for this variable anymore.

Here's an example of how the script might look (untested):
``` lisp
    (dialog-opts-push (format "+1 crew, +%@" c)
                      (lambda ()
                        (coins-add c)
                        (run-util-script   ; run a script from the utility folder
                         "find-crew-slot" ; name of script
                         "gah, out of space, etc. put that text here" ; text to show if there's no space
                         'ladder ; block to create if there's no space
                         (lambda (x y _) ; callback function, invoked with the x,y coordinates where we can safely place a character
                           (chr-new (player) x y 'neutral '((race . 1) (icon . 18))) ;create the character
                           (adventure-log-add 51 '()) ; write an entry into the adventure log
                           (dialog "One of the goblins joined your crew!") ; some dialog
                           (run-util-script "hostile-pickup-cart" ; run another utility script that gives us a data cart
                                            8
                                            "While scanning the goblin fortress' computers, you find some fascinating images of the surface world. You record them on a cartridge...")
                           (exit 2)))))  ; when dialog is finished, exit the level and show the victory screen

```

**Comment by evanbowman** [comment]
> > Actually tried with the utility script yesterday but didn't quite managed to understand how to implement it with the ss variable
> 
> The ss variable would no longer be needed. Sorry for the short variable names! An earlier version of the interpreter was unable to support variables longer than 4 letters, and there are still some old variable names that aren't very descriptive.
> 
> The ss variable holds slots that a character can be placed into.
> 
> The find-crew-slot script handles finding a slot or creating it if it doesn't exist, so there's no need for this variable anymore.
> 
> Here's an example of how the script might look (untested):
> 
> ```commonlisp
>     (dialog-opts-push (format "+1 crew, +%@" c)
>                       (lambda ()
>                         (coins-add c)
>                         (run-util-script   ; run a script from the utility folder
>                          "find-crew-slot" ; name of script
>                          "gah, out of space, etc. put that text here" ; text to show if there's no space
>                          'ladder ; block to create if there's no space
>                          (lambda (x y _) ; callback function, invoked with the x,y coordinates where we can safely place a character
>                            (chr-new (player) x y 'neutral '((race . 1) (icon . 18))) ;create the character
>                            (adventure-log-add 51 '()) ; write an entry into the adventure log
>                            (dialog "One of the goblins joined your crew!") ; some dialog
>                            (run-util-script "hostile-pickup-cart" ; run another utility script that gives us a data cart
>                                             8
>                                             "While scanning the goblin fortress' computers, you find some fascinating images of the surface world. You record them on a cartridge...")
>                            (exit 2)))))  ; when dialog is finished, exit the level and show the victory screen
> ```
``` lisp
                         'ladder
                         "Place block (1x2):"    ; <-- added line
                         (lambda (x y _)
```
seems it was missing a parameter

**Comment by Doronimmo** [comment]
updated the script : )
NOTE: the dialog text is placeholder

**Comment by Doronimmo** [comment]
> > > Actually tried with the utility script yesterday but didn't quite managed to understand how to implement it with the ss variable
> > 
> > 
> > The ss variable would no longer be needed. Sorry for the short variable names! An earlier version of the interpreter was unable to support variables longer than 4 letters, and there are still some old variable names that aren't very descriptive.
> > The ss variable holds slots that a character can be placed into.
> > The find-crew-slot script handles finding a slot or creating it if it doesn't exist, so there's no need for this variable anymore.
> > Here's an example of how the script might look (untested):
> > ```
> >     (dialog-opts-push (format "+1 crew, +%@" c)
> >                       (lambda ()
> >                         (coins-add c)
> >                         (run-util-script   ; run a script from the utility folder
> >                          "find-crew-slot" ; name of script
> >                          "gah, out of space, etc. put that text here" ; text to show if there's no space
> >                          'ladder ; block to create if there's no space
> >                          (lambda (x y _) ; callback function, invoked with the x,y coordinates where we can safely place a character
> >                            (chr-new (player) x y 'neutral '((race . 1) (icon . 18))) ;create the character
> >                            (adventure-log-add 51 '()) ; write an entry into the adventure log
> >                            (dialog "One of the goblins joined your crew!") ; some dialog
> >                            (run-util-script "hostile-pickup-cart" ; run another utility script that gives us a data cart
> >                                             8
> >                                             "While scanning the goblin fortress' computers, you find some fascinating images of the surface world. You record them on a cartridge...")
> >                            (exit 2)))))  ; when dialog is finished, exit the level and show the victory screen
> > ```
> 
> ```commonlisp
>                          'ladder
>                          "Place block (1x2):"    ; <-- added line
>                          (lambda (x y _)
> ```
> 
> seems it was missing a parameter

Is this dialog line always necessary?

**Comment by evanbowman** [comment]
> Is this dialog line always necessary?

Currently it's necessary, because the script expects it as a parameter. The script handles the scenarios where the game needs to create a new block when adding crew slots, so the script needs to know what text to display when doing so.

**Comment by evanbowman** [comment]
I think the changes look good. Can you remove some of the comments at the end of the lines? I added those comments in the example to explain what the script is doing, but the comments don't need to be committed to the repository.

**Comment by Doronimmo** [comment]
> I think the changes look good. Can you remove some of the comments at the end of the lines? I added those comments in the example to explain what the script is doing, but the comments don't need to be committed to the repository.

I think it might be useful as an example for how to use find-crew-slot since there is no documentation for utility scripts

**Comment by Doronimmo** [comment]
> I think the changes look good. Can you remove some of the comments at the end of the lines? I added those comments in the example to explain what the script is doing, but the comments don't need to be committed to the repository.

removed 5f22729

**Comment by evanbowman** [comment]
Looks ok in general. Looking at the diff, fs.bin and a few other files were committed, can you remove some of those?

**Comment by Doronimmo** [comment]
Added the images.cpp to gitignore

**Review by evanbowman — APPROVED** [review]

**Pull request merged**
