### PR TITLE
Normalized comments at start

### PR DESCRIPTION
**Pull request by Doronimmo**
;;;
;;; challengename.lisp
;;;

### CODE REVIEW

**Comment by evanbowman** [comment]
Thanks! I mainly put the filename at the top of the file so that I could remember which file I was looking at in the game's builtin text editor:
Skyland-98
I used this super limited text editor when I was developing the game to edit bugs in scripts on my gba while I was away from my computer.

**Comment by evanbowman** [comment]
Over time I got lazy about the file names at the top and sometimes forgot to adjust it.

**Review by evanbowman — APPROVED** [review]
Thank you! Approved, feel free to merge it yourself

**Comment by Doronimmo** [comment]
Whoa! Thanks!

**Comment by evanbowman** [comment]
I added you as a collaborator so you can merge these yourself now. Pull requests are still required and you won't be able to push directly to master. It saves me the trouble of having to approve the pr and then go back and merge it myself.

**Pull request merged**
