### PR TITLE
added default chr icons for some events

### PR DESCRIPTION
**Pull request by Doronimmo**

### CODE REVIEW

**Comment by evanbowman** [comment]
I appreciate your work here, but the list of changes is very large! I'm having some difficulty seeing what changed in this commit. I wonder if git for windows altered the line endings in every file or something

**Comment by Doronimmo** [comment]
> I appreciate your work here, but the list of changes is very large! I'm having some difficulty seeing what changed in this commit. I wonder if git for windows altered the line endings in every file or something

oh, this seems to be the case, some vscode nonsense

**Comment by evanbowman** [comment]
If it is a line ending issue, I think git itself has some configuration to prevent it from happening, I don't remember fully though

**Comment by Doronimmo** [comment]
looks like vscode commited all files when creating a new branch.

**Comment by evanbowman** [comment]
Overall, just going by the title, I think giving icons to characters who join your ship is a pretty good idea. I tried doing this in the past, before the game supported automated crew movement, but then I found myself avoiding using certain crew members because I didn't want them to die. Now that movement is automated, I think giving crewmembers icons is less of a psychological/game design issue than it used to be, let's try it out! We have to fix this giant diff first, though :)

**Comment by Doronimmo** [comment]
closing this pull request, will try to open again witout the diff

**Pull request closed without merging**
