### PR TITLE
Update backdoor.lisp

### PR DESCRIPTION
**Pull request by Doronimmo**
open the glossery automatically

### CODE REVIEW

**Review by evanbowman — APPROVED** [review]
Good idea!

**Comment by Doronimmo** [comment]
> Good idea!

There is some screen-tearing and the pause logo is showing through the glossary, is there a command to fix this?

**Comment by evanbowman** [comment]
> > Good idea!
> 
> There is some screen-tearing and the pause logo is showing through the glossary, is there a command to fix this?

Unfortunately these things can't be fixed with just the script api, the glossary viewer itself needs to be updates. In GlossaryViewerModule::enter(), a few changes can be made when entering the glossary viewer scene:
    `PLATFORM.fill_overlay(0);` Clear out any existing contents in the overlay tile layer. You'd want to do this at the beginning of the function.
```
PLATFORM.screen().fade(0.95f);
PLATFORM.screen().fade(1.f);
```
There was an old `fade` function in the codebase that ignores screen sync and creates tearing. Change these function calls to `schedule_fade`.

**Comment by evanbowman** [comment]
looks good to me

**Pull request merged**
