### PR TITLE
Revert "re-added changes in new branch"

### PR DESCRIPTION
**Pull request by Doronimmo**
Reverts evanbowman/skyland-beta#92 needs bug-testing

### CODE REVIEW

**Comment by evanbowman** [comment]
"Delete build/SkylandEngine"

It will be especially important, after you delete files like SkylandEngine and fs.bin from the diff, to use the squash commits option when merging, otherwise these files, although deleted, will still be stored in commits and make the repository bigger.
I use the emacs git plugin so I haven't had to worry about adding these files by accident, but they probably should be in the gitignore.

**Comment by evanbowman** [comment]
Skyland-166
I'm busy working on a few feature for displaying stats, but I can help test stuff when I have free time

**Comment by Doronimmo** [comment]
> Skyland-166 I'm busy working on a few feature for displaying stats, but I can help test stuff when I have free time

crewmember passport is a really cool idea!

**Review by evanbowman — APPROVED** [review]

**Comment by evanbowman** [comment]
Oh sorry! Looks like I also edited those scripts to make the same fixes, I should have looked at this PR first! Because we changed the same files, there are merge conflicts in two files.

**Comment by Doronimmo** [comment]
used chr icon .27 image insted of .1 image based on the dialog 
> In case it's helpful: in the dialog text, you'll see expressions like <c:name:number>. That number is the character icon number

**Pull request merged**
